# Generated by Django 5.1.6 on 2025-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='خالی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='خالی', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='خالی', max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_paid',
            field=models.IntegerField(default=0),
        ),
    ]
