# Generated by Django 5.1.6 on 2025-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
