# Generated by Django 5.1.6 on 2025-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_active_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_discount',
            field=models.IntegerField(default=0),
        ),
    ]
