# Generated by Django 5.1.6 on 2025-04-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoptions',
            options={'verbose_name': 'delivery Options', 'verbose_name_plural': 'delivery Options'},
        ),
    ]
