# Generated by Django 5.1.6 on 2025-04-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_deliveryoptions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
